/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DockerConfigJSONObservation struct {

	// SecretType definition - Server URL of the registry.
	ImageRegistryURL *string `json:"imageRegistryUrl,omitempty" tf:"image_registry_url,omitempty"`

	// SecretType definition - Username of the registry.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type DockerConfigJSONParameters struct {

	// SecretType definition - Server URL of the registry.
	// +kubebuilder:validation:Required
	ImageRegistryURL *string `json:"imageRegistryUrl" tf:"image_registry_url,omitempty"`

	// SecretType definition - Password of the registry.
	// +kubebuilder:validation:Required
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// SecretType definition - Username of the registry.
	// +kubebuilder:validation:Required
	Username *string `json:"username" tf:"username,omitempty"`
}

type KubernetesSecretMetaObservation struct {

	// Annotations for the resource
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Description of the resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels for the resource
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// Resource version of the resource
	ResourceVersion *string `json:"resourceVersion,omitempty" tf:"resource_version,omitempty"`

	// UID of the resource
	UID *string `json:"uid,omitempty" tf:"uid,omitempty"`
}

type KubernetesSecretMetaParameters struct {

	// Annotations for the resource
	// +kubebuilder:validation:Optional
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// Description of the resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Labels for the resource
	// +kubebuilder:validation:Optional
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`
}

type KubernetesSecretObservation struct {

	// Export the secret to all namespaces.
	Export *bool `json:"export,omitempty" tf:"export,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Metadata for the resource
	Meta []KubernetesSecretMetaObservation `json:"meta,omitempty" tf:"meta,omitempty"`

	// Name of the secret resource.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Name of Namespace where secret will be created.
	NamespaceName *string `json:"namespaceName,omitempty" tf:"namespace_name,omitempty"`

	// ID of Organization.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Scope for the secret having one of the valid scopes for secret: currently we have only cluster scope
	Scope []KubernetesSecretScopeObservation `json:"scope,omitempty" tf:"scope,omitempty"`

	// Spec for the kubernetes secret
	Spec []KubernetesSecretSpecObservation `json:"spec,omitempty" tf:"spec,omitempty"`

	// Status for the Secret Export.
	Status map[string]*string `json:"status,omitempty" tf:"status,omitempty"`
}

type KubernetesSecretParameters struct {

	// Export the secret to all namespaces.
	// +kubebuilder:validation:Optional
	Export *bool `json:"export,omitempty" tf:"export,omitempty"`

	// Metadata for the resource
	// +kubebuilder:validation:Optional
	Meta []KubernetesSecretMetaParameters `json:"meta,omitempty" tf:"meta,omitempty"`

	// Name of the secret resource.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Name of Namespace where secret will be created.
	// +kubebuilder:validation:Optional
	NamespaceName *string `json:"namespaceName,omitempty" tf:"namespace_name,omitempty"`

	// ID of Organization.
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Scope for the secret having one of the valid scopes for secret: currently we have only cluster scope
	// +kubebuilder:validation:Optional
	Scope []KubernetesSecretScopeParameters `json:"scope,omitempty" tf:"scope,omitempty"`

	// Spec for the kubernetes secret
	// +kubebuilder:validation:Optional
	Spec []KubernetesSecretSpecParameters `json:"spec,omitempty" tf:"spec,omitempty"`
}

type KubernetesSecretScopeClusterObservation struct {

	// Name of this cluster
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// Name of the management cluster
	ManagementClusterName *string `json:"managementClusterName,omitempty" tf:"management_cluster_name,omitempty"`

	// Provisioner of the cluster
	ProvisionerName *string `json:"provisionerName,omitempty" tf:"provisioner_name,omitempty"`
}

type KubernetesSecretScopeClusterParameters struct {

	// Name of this cluster
	// +kubebuilder:validation:Required
	ClusterName *string `json:"clusterName" tf:"cluster_name,omitempty"`

	// Name of the management cluster
	// +kubebuilder:validation:Optional
	ManagementClusterName *string `json:"managementClusterName,omitempty" tf:"management_cluster_name,omitempty"`

	// Provisioner of the cluster
	// +kubebuilder:validation:Optional
	ProvisionerName *string `json:"provisionerName,omitempty" tf:"provisioner_name,omitempty"`
}

type KubernetesSecretScopeObservation struct {

	// The schema for cluster secret full name
	Cluster []KubernetesSecretScopeClusterObservation `json:"cluster,omitempty" tf:"cluster,omitempty"`
}

type KubernetesSecretScopeParameters struct {

	// The schema for cluster secret full name
	// +kubebuilder:validation:Optional
	Cluster []KubernetesSecretScopeClusterParameters `json:"cluster,omitempty" tf:"cluster,omitempty"`
}

type KubernetesSecretSpecObservation struct {

	// SecretType definition - SECRET_TYPE_DOCKERCONFIGJSON, Kubernetes secrets type.
	DockerConfigJSON []DockerConfigJSONObservation `json:"dockerConfigJson,omitempty" tf:"docker_config_json,omitempty"`
}

type KubernetesSecretSpecParameters struct {

	// SecretType definition - SECRET_TYPE_DOCKERCONFIGJSON, Kubernetes secrets type.
	// +kubebuilder:validation:Required
	DockerConfigJSON []DockerConfigJSONParameters `json:"dockerConfigJson" tf:"docker_config_json,omitempty"`
}

// KubernetesSecretSpec defines the desired state of KubernetesSecret
type KubernetesSecretSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KubernetesSecretParameters `json:"forProvider"`
}

// KubernetesSecretStatus defines the observed state of KubernetesSecret.
type KubernetesSecretStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KubernetesSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// KubernetesSecret is the Schema for the KubernetesSecrets API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tmc}
type KubernetesSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.namespaceName)",message="namespaceName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.scope)",message="scope is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.spec)",message="spec is a required parameter"
	Spec   KubernetesSecretSpec   `json:"spec"`
	Status KubernetesSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KubernetesSecretList contains a list of KubernetesSecrets
type KubernetesSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KubernetesSecret `json:"items"`
}

// Repository type metadata.
var (
	KubernetesSecret_Kind             = "KubernetesSecret"
	KubernetesSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KubernetesSecret_Kind}.String()
	KubernetesSecret_KindAPIVersion   = KubernetesSecret_Kind + "." + CRDGroupVersion.String()
	KubernetesSecret_GroupVersionKind = CRDGroupVersion.WithKind(KubernetesSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&KubernetesSecret{}, &KubernetesSecretList{})
}
